### ISSUE TITLE
Could you please add support for MacOS ?

### ISSUE THREAD

**Issue by cyberpsyche** [EIRTeam/EIRTeam.FFmpeg#1]
Thank you~~

**Comment by EIREXE** [comment]
I do not have an apple device to test, but it should be relatively straightforward

**Comment by cyberpsyche** [comment]
Your source code seems only compatible with FFMpeg 5/6. Could FFMpeg 3 or 4 fit for your code ?

**Comment by EIREXE** [comment]
Not sure what has changed between 3 and 4 and 5/6, if there are API changes then yeah some things would have to be changed i think

**Comment by chaeyan** [comment]
any update on Mac support??

**Comment by EIREXE** [comment]
> any update on Mac support??

Should be made usable on macos without much work, but it needs to be done, I do not have a device with macOS myself so I can't really test it.

**Comment by chaeyan** [comment]
well, it might be working for macos but it doesnt work for the arm64 ones
