### ISSUE TITLE
there is no plugin

### ISSUE THREAD

**Issue by theBSH** [EIRTeam/EIRTeam.FFmpeg#15]
there is not even a plugin script so you can't use the extension.

**Comment by EIREXE** [comment]
What do you mean? for GDExtension no .gd files are needed

**Comment by theBSH** [comment]
how do i add the video player ? in the docs it says add it like a node but it doesn't exist

**Comment by EIREXE** [comment]
> how do i add the video player ? in the docs it says add it like a node but it doesn't exist

You just need to add the typical videostreamplayer node: https://docs.godotengine.org/en/stable/classes/class_videostreamplayer.html

**Comment by theBSH** [comment]
sorry i thought it was a separate node it would be good to add this as a node in the docs.
