### ISSUE TITLE
Only audio plays

### ISSUE THREAD

**Issue by gpaladino** [EIRTeam/EIRTeam.FFmpeg#19]
Hi,
I'm unable to get it work correctly in godot 4.2.1, plugins says:

Succesfully initialized video decoder:h264
MAKE SHADER
CRECREATE OUTPUT TEXTURE

But only audio plays, am i missing something?
Thanks

**Comment by EIREXE** [comment]
Hi, you should use the previous version if you are using 4.2, since current master depends on a PR that AFAIK hasn't been backported.

https://github.com/EIRTeam/EIRTeam.FFmpeg/releases/tag/autobuild-2023-12-04-05-43

**Comment by gpaladino** [comment]
It's working now thanks, 
And thanks also for the great work,
