### ISSUE TITLE
stream_position property support is missing ?

### ISSUE THREAD

**Issue by cyberpsyche** [EIRTeam/EIRTeam.FFmpeg#2]
Hi @EIREXE , thanks for your work on this GDExtension.  Ultimately I could run it on my machine.  :)

But I found that the VideoStreamPlayer node cannot set 'stream_position' property in gdscript. The code just overlook this setting and always play the stream from the very beginning. As stream_position is a very very important property of the stream playback, will you please add this feature in your code?

Thanks!

**Comment by EIREXE** [comment]
How are you setting the stream_position? I myself have found that setting it using set_stream_position fails, but just setting the stream_position property works fine

**Comment by cyberpsyche** [comment]
I set the stream_position property by this kind of code snippet:

```
	var ffmpeg_stream = FFmpegVideoStream.new()
	ffmpeg_stream.file = "/Users/chris/media/seeyou.mp4"	
	$VideoStreamPlayer.stream = ffmpeg_stream
	$VideoStreamPlayer.stream_position = 2.0
	$VideoStreamPlayer.play()
```

Any suggestion?

**Comment by EIREXE** [comment]
> I set the stream_position property by this kind of code snippet:
> 
> ```
> 	var ffmpeg_stream = FFmpegVideoStream.new()
> 	ffmpeg_stream.file = "/Users/chris/media/seeyou.mp4"	
> 	$VideoStreamPlayer.stream = ffmpeg_stream
> 	$VideoStreamPlayer.stream_position = 2.0
> 	$VideoStreamPlayer.play()
> ```
> 
> Any suggestion?

try calling play() before seeking, that should work

**Comment by zedrun00** [comment]
Hi, How get video length in gds ? my need set stream_position in **HSlider** Node by percentage

**Comment by EIREXE** [comment]
> Hi, How get video length in gds ? my need set stream_position in **HSlider** Node by percentage @EIREXE

I think the ability to get the length was removed in 4.0 or was never there in the first place, not sure why.

**Comment by zedrun00** [comment]
Regrettably, so is there any other way, can make a video progress bar?

**Comment by EIREXE** [comment]
> This is regrettable, So is there any other way, can make a video progress bar? @EIREXE

For the time being I think you'll have to figure out the time externally and bake it in, or modify the engine to add an API to get the length

**Comment by zedrun00** [comment]
> > This is regrettable, So is there any other way, can make a video progress bar? @EIREXE
> 
> For the time being I think you'll have to figure out the time externally and bake it in, or modify the engine to add an API to get the length

I can't, I don't have the ability to modify the engine right now.  If you make it.  call me， thank you！ :)

**Comment by rsubtil** [comment]
AFAICT there was never a way to get the video stream length, despite Godot 3.x having a `get_length` field.

The godot-videodecoder uses a hack where you seek to a negative value to find the video length:
https://github.com/kidrigger/godot-videodecoder/blob/af71383dce66eea88f3ce99b416613b925be3ba0/src/gdnative_videodecoder.c#L1086-L1089

I do think that this issue has been here for too long for something that is simple, so I'll look into getting this finally implemented in Godot.

**Comment by rsubtil** [comment]
Oh, nevermind, this got merged recently (https://github.com/godotengine/godot/pull/77858), so this should now be possible to implement.

**Comment by trekfan42** [comment]
So seeking is working mostly, but it's inconsistent and i get this error often when seeking with a HSlider:

Video too far out of sync (1900.00), seeking to 25050.22
Video too far out of sync (28940.67), seeking to 53050.65
Video too far out of sync (53074.67), seeking to 56216.58
Video too far out of sync (53141.33), seeking to 56250.49

**Comment by trekfan42** [comment]
> AFAICT there was never a way to get the video stream length, despite Godot 3.x having a `get_length` field.
> 
> The godot-videodecoder uses a hack where you seek to a negative value to find the video length: https://github.com/kidrigger/godot-videodecoder/blob/af71383dce66eea88f3ce99b416613b925be3ba0/src/gdnative_videodecoder.c#L1086-L1089
> 
> I do think that this issue has been here for too long for something that is simple, so I'll look into getting this finally implemented in Godot.

this is my solution:

```
func ffprobe(path):
	print( "checking duration of video at: " + path)
	var ffprobe = ProjectSettings.globalize_path("res://ffprobe.exe")
	var args = ["-v", "error", "-select_streams", "v:0", "-show_entries", "format=duration", "-of", "default=noprint_wrappers=1", path ]
	# ffprobe.exe -v error -select_streams v:0 -show_entries format=duration -of default=noprint_wrappers=1 test.mp4
	var output = []
	
	var result = OS.execute(ffprobe,args,output,true,false)
	
	var dur0 = output[0]
	var dur1 = dur0.replace("duration=","")
	var dur2 = dur1.replace("\r\n","")
	var videoLength = round(float(dur2))
	print("execute result: " + str(videoLength))
	
	return videoLength
```

**Comment by trekfan42** [comment]
So seeking is working mostly, but it's inconsistent and i get this error often when seeking with a HSlider:

Video too far out of sync (1900.00), seeking to 25050.22
Video too far out of sync (28940.67), seeking to 53050.65
Video too far out of sync (53074.67), seeking to 56216.58
Video too far out of sync (53141.33), seeking to 56250.49

**Comment by EIREXE** [comment]
> So seeking is working mostly, but it's inconsistent and i get this error often when seeking with a HSlider:
> 
> Video too far out of sync (1900.00), seeking to 25050.22 Video too far out of sync (28940.67), seeking to 53050.65 Video too far out of sync (53074.67), seeking to 56216.58 Video too far out of sync (53141.33), seeking to 56250.49
> 
> https://streamable.com/4usyih
> 
> It seems like if i try to seek too far, i get the error and it never recovers, but then i can go back to the beginning and recover

Are you constantly seeking or only seeking when letting go?

**Comment by EIREXE** [comment]
> Oh, nevermind, this got merged recently ([godotengine/godot#77858](https://github.com/godotengine/godot/pull/77858)), so this should now be possible to implement.

Currently on vacation but I'll implement it as soon as I return

**Comment by trekfan42** [comment]
> > So seeking is working mostly, but it's inconsistent and i get this error often when seeking with a HSlider:
> > Video too far out of sync (1900.00), seeking to 25050.22 Video too far out of sync (28940.67), seeking to 53050.65 Video too far out of sync (53074.67), seeking to 56216.58 Video too far out of sync (53141.33), seeking to 56250.49
> > https://streamable.com/4usyih
> > It seems like if i try to seek too far, i get the error and it never recovers, but then i can go back to the beginning and recover
> 
> Are you constantly seeking or only seeking when letting go?

On slider drag start I pause. Then on drag finish I seek to the slider value.

**Comment by EIREXE** [comment]
> > > So seeking is working mostly, but it's inconsistent and i get this error often when seeking with a HSlider:
> > > Video too far out of sync (1900.00), seeking to 25050.22 Video too far out of sync (28940.67), seeking to 53050.65 Video too far out of sync (53074.67), seeking to 56216.58 Video too far out of sync (53141.33), seeking to 56250.49
> > > https://streamable.com/4usyih
> > > It seems like if i try to seek too far, i get the error and it never recovers, but then i can go back to the beginning and recover
> > 
> > 
> > Are you constantly seeking or only seeking when letting go?
> 
> On slider drag start I pause. Then on drag finish I seek to the slider value.
> 
> ```
> func _on_play_slider_drag_ended(value_changed):
> 	videoBox.set_stream_position(playslider.value)
> 	seeking = false
>         videoBox.paused = false
> 
> func _on_play_slider_drag_started():
> 	videoBox.paused = true
> 	seeking = true
> ```
> 
> Also not sure if its related but it's also usually correlated to the audio playing first then the video, so there is a desync, then i have to pause and wait for it to catch up then I can play again in sync. sometimes the video comes back but with no audio and i have to reload the path and position to get audio back
> 
> but sometimes if I drag too far away from the current position, I never get audio or video, just that out of sync error message

strange, i'll take a look when i can

**Comment by EIREXE** [comment]
@zedrun00 please try the new release, it should now return the length in the correct units

Also @trekfan42 let me know if it seeks better now, i made some changes.

**Comment by trekfan42** [comment]
@EIREXE Holy crap! what an improvement!!!

Thanks for working on this! 
I can now continue my project!

and with the new length return I can remove this workaround! https://github.com/EIRTeam/EIRTeam.FFmpeg/issues/2#issuecomment-1670134427

**Comment by trekfan42** [comment]
The only issues I'm having now are some videos do this where the lines are offset and results in a skewed diagonal look
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/14896909/50c12d99-8d91-4467-a7dc-a0316a870100)


and some videos have audio issues like static crackling sounding playback...

Trying to find the common denominator in the codecs at the moment.

**Comment by EIREXE** [comment]
> The only issues I'm having now are some videos do this where the lines are offset and results in a skewed diagonal look ![image](https://user-images.githubusercontent.com/14896909/268459014-50c12d99-8d91-4467-a7dc-a0316a870100.png)
> 
> and some videos have audio issues like static crackling sounding playback...
> 
> Trying to find the common denominator in the codecs at the moment.

If you could send me a sample video to take a look at I could try to reproduce the issue.

**Comment by trekfan42** [comment]
I'm currently unable to call get_length() on VideoStreamPlayer
Running 4.1.1. and latest of this release... am i doing something wrong?

**Comment by EIREXE** [comment]
> I'm currently unable to call get_length() on VideoStreamPlayer Running 4.1.1. and latest of this release... am i doing something wrong?

I think it may only be available in 4.2 and not be exposed to scripting in 4.1

**Comment by trekfan42** [comment]
oh okay, yup,  get_stream_length() returns it in seconds. cool!

I saw you had mentioned using an older ffmpeg library or something for compatibility...

Would you be able to walk me through updating the ffmpeg library to use a more recent version so I can decode more codecs? Is that a complex task or does it involve just replacing a dll or something?

**Comment by EIREXE** [comment]
> oh okay, yup, get_stream_length() returns it in seconds. cool!
> 
> I saw you had mentioned using an older ffmpeg library or something for compatibility...
> 
> Would you be able to walk me through updating the ffmpeg library to use a more recent version so I can decode more codecs? Is that a complex task or does it involve just replacing a dll or something?

Actually it doesn't use an old version of ffmpeg, you can just find any other dll/so of ffmpeg 6 and drop it in and it will work.

However, beware, as some codecs might be patent encumbered.

**Comment by trekfan42** [comment]
Good to know thanks, I'll give it a whirl

**Comment by trekfan42** [comment]
Silly question, how do i acquire the dlls?

**Comment by EIREXE** [comment]
> Silly question, how do i acquire the dlls?

This repo has some builds that should work: https://github.com/BtbN/FFmpeg-Builds

**Comment by trekfan42** [comment]
The readme says this:
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/14896909/1dd0bd7b-3a54-448b-a921-64177d96556a)

but when i download it there are just exe's no files like the one you include:
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/14896909/45b86e33-3b47-4c0e-b915-3d7cab8724fc)

**Comment by EIREXE** [comment]
> The readme says this: ![image](https://user-images.githubusercontent.com/14896909/269054151-1dd0bd7b-3a54-448b-a921-64177d96556a.png)
> 
> but when i download it there are just exe's no files like the one you include: ![image](https://user-images.githubusercontent.com/14896909/269054529-45b86e33-3b47-4c0e-b915-3d7cab8724fc.png)

I see dlls on the left, those are the ones you are supposed to copy

**Comment by trekfan42** [comment]
I thought I would need new ones for the libglffmpeg dlls...

**Comment by EIREXE** [comment]
Nice! Closing this now as it should be fine me thinks
