### ISSUE TITLE
There are some problems with compilation

### ISSUE THREAD

**Issue by ModuleCode** [EIRTeam/EIRTeam.FFmpeg#21]
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/46812028/80129507-4725-4dcc-b3b2-a2759ef9b59c)

**Comment by EIREXE** [comment]
Did you update he git submodules?

**Comment by ModuleCode** [comment]
The problem is solved .I directly cloned the project and compiled it. I found that the godot-cpp folder was empty.
