### ISSUE TITLE
Is .mov supported?

### ISSUE THREAD

**Issue by htang63** [EIRTeam/EIRTeam.FFmpeg#3]
When i try to play a .mov file it crashes. Is mov not supported or could it be a codec issue? I was trying to use codec ProRes4444 with alpha channel.

**Comment by EIREXE** [comment]
You will need to use a distribution of the ffmpeg library that has more codecs enabled, you can try using the LGPL builds fuond [here](https://github.com/BtbN/FFmpeg-Builds/releases)

**Comment by htang63** [comment]
Thank you very much and great job with this plugin
