### ISSUE TITLE
WebM transparent video support ？

### ISSUE THREAD

**Issue by juntaosun** [EIRTeam/EIRTeam.FFmpeg#38]
Great project.
I tested WebM transparent video, which contains BGRA channels, but after decoding with EIRTeam.FFmpeg, the pixels obtained only have BGR channels. The transparent pixels are lost. 

Can you add the preservation and support of WebM transparent channels in future versions? Thank you!

```
yuv420p

yuva420p  （transparent）
```

Alpha transparency in Chrome video：
[https://developer.chrome.com/blog/alpha-transparency-in-chrome-video?hl=en](url)

using an ffmpeg command like this: （PNG files to a YUVA video）
```
ffmpeg -i image%04d.png output.webm
```

By the way, it has been more than 4 months since the last update. 
When will there be another update?

**Comment by EIREXE** [comment]
I added support for YUVA on the newest update, however you'll need a version of ffmpeg that has libvpx built in as ffmpeg's normal vp decoder doesn't support alpha.

**Comment by EIREXE** [comment]
I'll take a look, I didn't make the android port so I'm not very familiar with it

**Comment by bestvcboy** [comment]
> Thanks for the quick reply, I can't get the plugin for Android. I tried to pull the source code and compile it, the compile environment is already installed, but it gives an error (compilation failed). Can you release Android?
> 
> ![{0D9B8629-8102-4DE3-B2EF-96C2F4A99962}](https://private-user-images.githubusercontent.com/22288197/380486551-11a71eb9-f612-4776-9097-8f0a1b48e411.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5NzIxMjksIm5iZiI6MTczMDk3MTgyOSwicGF0aCI6Ii8yMjI4ODE5Ny8zODA0ODY1NTEtMTFhNzFlYjktZjYxMi00Nzc2LTkwOTctOGYwYTFiNDhlNDExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDA5MzAyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwZDlhZjYzMDY4OWU4ZjM5ODg0OTQyYzNiNTIxOGQzMWY3YTJhOWM3MWM1ZTVlYWZlNjBkYzFmYmNhNmQzNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LvGXftyfGrnJJeh6XlphVeyRCCWKLBwWk8K-vkce5_I)
> 
> What is the version number of the FFMPEG library currently used?


 
Have you succeeded on Android? If successful, would it be convenient to share it? I also want one.

**Comment by EIREXE** [comment]
Closing this as the issue it refers to is fixed (I think), pls make another issue for android stuff if needed.

(I still haven't taken a look at it, but I haven't forgotten).
