### ISSUE TITLE
File selection at runtime

### ISSUE THREAD

**Issue by VampireSqu1d** [EIRTeam/EIRTeam.FFmpeg#39]
Hi I'm trying to use a file dialog to select a file to give to the video stream. I create a new FFmpegVideoStream and set its file property to the file selected by the dialog but the video streamer fails to play the video. Idk if its a real bug or the file property is not designed to be used as I'm trying to.
I'm attaching a project with what I'm trying to do.
Great addon btw!
[VideoPlayback.zip](https://github.com/user-attachments/files/17612348/VideoPlayback.zip)

**Comment by VampireSqu1d** [comment]
System info: Godot v4.3.stable - Windows 10.0.19045 - Vulkan (Forward+) - dedicated NVIDIA GeForce GTX 1050 Ti (NVIDIA; 32.0.15.6590) - Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 Threads)

**Comment by Avatarchik** [comment]
Hi!
add video launch to the code:

video_stream_player.play()

**Comment by VampireSqu1d** [comment]
Hi!
thanks for the response, I guess I should've tried that.
Great Extension btw!
