### ISSUE TITLE
Replacing the ffmpeg dlls to achieve alpha channel support

### ISSUE THREAD

**Issue by koenheltzel** [EIRTeam/EIRTeam.FFmpeg#40]
Hi!
I'm very excited to use the plugin, but I really need alpha channel support in my project. I'm developing on Windows 10.

[Here](https://eirteam-docs.readthedocs.io/en/latest/documentation/ffmpeg/ffmpeg_getting_started.html) there's mention of "replacing" .dll files and that "The LGPL builds found [here](https://github.com/BtbN/FFmpeg-Builds/releases)" should also be compatible. A pre-built replacement sounds good to me. I picked the 6.1 lgpl shared build because the .dll names in the bin folder (avcodec-60.dll, avfilter-9.dll etc) match the ones in your latest build. However those builds don't contain a libgdffmpeg.windows.template_release.x86_64.dll equivalent but instead an executable (ffmpeg.exe):

![image](https://github.com/user-attachments/assets/5cab525e-da8e-4072-807b-8c86d455bb6f)

I'm a trial and error kind of person, so I tried copying the .dll files that are there to the addon folder. If I then run my Godot project, I see a lot more "Supported video codecs" being printed, but  I'm met with this error:
```
VideoDecoder::recreate_codec_context: Couldn't copy codec parameters from h264: **Cannot allocate memory**
  <C++ Error>    Condition "param_copy_result < 0" is true. Returning: FAILED
  <C++ Source>   D:\a\EIRTeam.FFmpeg\EIRTeam.FFmpeg\video_decoder.cpp:203 @ VideoDecoder::recreate_codec_context()
```

So, am I misunderstanding that those [builds](https://github.com/BtbN/FFmpeg-Builds/releases) are a drop-in replacement and you have to build the ffmpeg dll yourself?

Thank you very kindly for the work you've done and for looking into my noob issue!
- Koen

**Comment by vickyorlo** [comment]
The ffmpeg auto-builds that the prebuilt package is built against (https://github.com/EIRTeam/ffmpeg-builds/) haven't been rebuilt for over a year and it seems FFmpeg has gotten an incompatible upgrade since. You should be able to fix this by building this addon yourself, but I havent tried. It would be nice if the official builds were updated so it would be possible to switch the dlls around quickly.

**Comment by koenheltzel** [comment]
Thank you @vickyorlo, great to hear from you!
Those builds you point to in your edit do "work" as in they can show a transparent video!

However, in the Output tab there is "25" printed every frame (maybe the framerate?).
Also there is this error every frame:
```
connect: In Object of type 'RefCounted': Attempt to connect nonexistent signal 'return_frame' to callable '<CallableCustom>'.
  <C++ Error>    Condition "!signal_is_valid" is true. Returning: ERR_INVALID_PARAMETER
  <C++ Source>   core/object/object.cpp:1390 @ connect()
```
Finally, there's a specific video (actually the first one I tried) that causes the process to stop after about 3 seconds.

[Here is a minimum reproduction project](https://we.tl/t-4XL6zMmWIJ), this uses (and includes) this ffmpeg build's dlls:
ffmpeg-n6.0-32-gd4a7a6e7fa-win64-lgpl-shared-6.0.zip
The project includes 2 .mov files and VideoStreamPlayer nodes autoplaying and looping them.
The "freeplay" one causes the process to stop after 3 seconds. If you delete that node the process will run longer with just the "warning" animation looping.
Note the output and errors.

Thank you very kindly again!
- Koen

**Comment by koenheltzel** [comment]
To be clear, the output and errors don't occur with a "normal" .mp4 video, so it is somehow related to the codec or maybe the transparency.

**Comment by EIREXE** [comment]
It is now fixed, do note that the file you posted is encoded using ARGB, which currently is converted using the CPU, if you switch to using YUVA 4:2:0 you will have many performance benefits, but this might not matter depending on your use case.

**Comment by EIREXE** [comment]
Should be fine with the latest release.

**Comment by koenheltzel** [comment]
Wow @EIREXE, I'm impressed and very grateful! Thank you for the note on ARGB as well.
Heading to your Patreon now!

**Comment by EIREXE** [comment]
> Wow @EIREXE, I'm impressed and very grateful! Thank you for the note on ARGB as well. Heading to your Patreon now!

Thank you very much!
