### ISSUE TITLE
Replaying a video will first show the last shown frame of the previous play

### ISSUE THREAD

**Issue by koenheltzel** [EIRTeam/EIRTeam.FFmpeg#42]
Hello @EIREXE and contributors,

When a video has finished or was stopped and then played again, the last shown frame of the previous play is still visible before the first frame is shown.
This is most obvious when you hide the VideoStreamPlayer on the finished signal or when stopping the video, and showing it again when playing it.
Of course this could be a performance thing, but it's annoying the VideoStreamPlayer node is not empty the way it is when you first play the video. If this could be somehow fixed in the plugin that would be great, if not what would be good workaround?
I tried a workaround like this:
```
video_stream_player.play()  # video_stream_player is currently hidden
await get_tree().create_timer(4/60.0).timeout
video_stream_player.show()
```
And that sort of works, but the "4" magic number is just a guesstimate and can change per video or computer.
I also tried clearing the node as it is a CanvasItem by doing a .draw_rect but that doesn't seem to have any effect.

[Here is a minimum reproduction project](https://we.tl/t-2S4lcWqHUx), which uses plugin v1.1.2 (with stock dlls).
This project shows the behavior of a .ogv file being handled by Godot (I think?) and a .mp4 file being handled through the plugin.
After the videos have finished or are stopped the VideoStreamPlayer nodes are hidden until pressing the play button. You will see the last frame of the .mp4 video flicker before its first frame is shown, while the .ogv does not.

Best regards,

Koen

**Comment by koenheltzel** [comment]
Thanks @EIREXE for the quick fix again. However the fix has 2 negative effects I can gather so far:
- Transparant videos don't show up anymore (no errors either, just the videos are not visible).
- A looping video will show a clear frame when looping back to the beginning, making seemless loops no longer seemless.
Kind regards,
Koen

**Comment by EIREXE** [comment]
> Thanks @EIREXE for the quick fix again. However the fix has 2 negative effects I can gather so far:
> 
>     * Transparant videos don't show up anymore (no errors either, just the videos are not visible).
> 
>     * A looping video will show a clear frame when looping back to the beginning, making seemless loops no longer seemless.
>       Kind regards,
>       Koen


I'll take a look, are you sure you didn't accidentally replace your ffmpeg libraries when updating it? that could have reverted you to the very lean ffmpeg build PH uses

**Comment by koenheltzel** [comment]
Thanks in advance. Yes I'm 100% sure, I only replace the libgdffmpeg.windows.template_* files and just double checked as well.

**Comment by koenheltzel** [comment]
Dear @EIREXE, could you please take another look at this. The latest release isn't really usable, even though it might fix this issue, it breaks others.
See my [comment](https://github.com/EIRTeam/EIRTeam.FFmpeg/issues/42#issuecomment-2481607509) from Nov 17, 2024 above.

Thank you for your time.

**Comment by EIREXE** [comment]
> Dear [@EIREXE](https://github.com/EIREXE), could you please take another look at this. The latest release isn't really usable, even though it might fix this issue, it breaks others. See my [comment](https://github.com/EIRTeam/EIRTeam.FFmpeg/issues/42#issuecomment-2481607509) from Nov 17, 2024 above.
> 
> Thank you for your time.

Sorry I recently got hired and I've been super busy, I'll take a look when I can!
