### ISSUE TITLE
Diagonal Skewed lines Issue

### ISSUE THREAD

**Issue by trekfan42** [EIRTeam/EIRTeam.FFmpeg#5]
Just wanted to follow up on the issue from the other thread...

There are a few videos that I have that look diagonally skewed... every next line is shifter over to the right.
Here's what it looks like:
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/14896909/c5c51858-37ab-4f8d-8d79-ecdb383de091)

So in this picture, the 2 on the left are videos that are diagonally skewed... and the 2 on the right are fine.
There is an m4v and mp4 example for each:
![image](https://github.com/EIRTeam/EIRTeam.FFmpeg/assets/14896909/ad7f493f-fc2e-4467-8444-ac4e27037d96)

Here is a link to an m4v that is doing this: https://drive.google.com/file/d/15JGGat5iTH9Gv5Vn9ph3AYgrOaAE292d/view?usp=sharing
if you want to inspect it

**Comment by EIREXE** [comment]
I'll take a look ASAP
