### ISSUE TITLE
Engine Freezes Indefinitely when Invalid File is Used for the Stream

### ISSUE THREAD

**Issue by Setadokalo** [EIRTeam/EIRTeam.FFmpeg#6]
If you provide a filetype that ffmpeg can't load as a video, upon calling `play()` on the VideoStreamPlayer, the engine will freeze indefinitely without any error message. Ideally this should just error out.

**Comment by EIREXE** [comment]
Fixed in 1f54ef083102a3ab58f6e31048861a7395c0fcce
